version: '2'
services:
  rs1: &mongo
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEA
    command: mongod --dbpath /data/db --replSet my-mongo-set
    volumes:
      - rs1-data:/data/db
    ports:
      - 27217:27017
  rs2:
    <<: *mongo
    volumes:
      - rs2-data:/data/db
    ports:
      - 27218:27017
  rs3:
    <<: *mongo
    volumes:
      - rs3-data:/data/db
    ports:
      - 27219:27017

  mongo-express:
    image: mongo-express:latest
    restart: always
    links:
      - rs1:mongo
    environment:
      - VIRTUAL_HOST=${MONGOEXPRESS_URL}
      - VIRTUAL_PORT=8081
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEA
      # - ME_CONFIG_BASICAUTH_USERNAME=root
      # - ME_CONFIG_BASICAUTH_PASSWORD=2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEA

networks:
  default:
    external:
      name: sahaba

volumes:
  rs1-data:
  rs2-data:
  rs3-data:


# db.auth("root, "2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEA")
