version: '2'
services:
  mongo:
    image: mongo:latest
    volumes:
      - rs1-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEA
    ports:
      - 27217:27017
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000

  mongo-express:
    image: mongo-express:latest
    restart: always
    links:
      - mongo:mongo
    environment:
      - VIRTUAL_HOST=${MONGOEXPRESS_URL}
      - VIRTUAL_PORT=8081
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEA
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEA

networks:
  default:
    external:
      name: sahaba

volumes:
  rs1-data:
